### ISSUE TITLE
BUG - transaction time Today, yesterday 

### ISSUE THREAD

**Issue by albertorizzi** [flow-mn/flow#128] opened 2024-03-31 22:12 UTC
### Bug Description

As you can see in the attached screen, there are problems with days. The transaction of 31/03 is labeled with today, instead a transaction of 30/03 is labeled with yesterday.

### How to Reproduce

Create a transaction

### Expected Behavior

For the transaction of 30/03 yesterday for example

### Operating System

iOS 17

### Flow version (version+build number)

0.4.1+38

### Screenshots

![IMG_7369](https://github.com/flow-mn/flow/assets/48057685/4da7d70f-632f-4b4d-8f28-4315765f2f92)
![IMG_7368](https://github.com/flow-mn/flow/assets/48057685/0d960304-1772-419e-b788-541cbd8ffac9)
![IMG_7367](https://github.com/flow-mn/flow/assets/48057685/f751e47b-bc85-4147-9d13-f9d8b0ed1a8b)

**Comment by sadespresso** [comment] 2024-04-01 13:58
Hello @albertorizzi, thank you for the report :D :D 

Is the transaction still 1 day off?

I can't reproduce, I'll try to reproduce when my clock is around 12AM 😆

**Comment by albertorizzi** [comment] 2024-04-01 14:46
Yes, it is 1 day off.

Also now ![image](https://github.com/flow-mn/flow/assets/48057685/b51f4166-38a9-4ec8-a27a-01a64d2e71df)

**Comment by sadespresso** [comment] 2024-04-01 16:11
I still can't reproduce.

I'm guessing it may have to do something with time zones. I'll check the code for any such possibilities.

**Comment by albertorizzi** [comment] 2024-04-01 16:41
I attach you the json created by the backup of these transactions

```
{
      "uuid": "c2d3de2f-cba6-48fc-a4dd-b3a4d92499b1",
      "createdDate": "2024-04-01T00:01:41.568",
      "transactionDate": "2024-03-31T05:30:00.000",
      "title": "Schiacciata Florian",
      "amount": -5.0,
      "currency": "EUR",
      "subtype": null,
      "extra": null,
      "categoryUuid": "61ef5e53-203f-4475-810e-0c937eeee762",
      "accountUuid": "0e31f1f6-aacd-42f9-adbe-99321b0a2953"
    },
    {
      "uuid": "6e151c34-5f58-4b2e-856f-0ac0236d2866",
      "createdDate": "2024-04-01T18:26:22.679",
      "transactionDate": "2024-04-01T18:26:10.223",
      "title": "test",
      "amount": -5.5,
      "currency": "EUR",
      "subtype": null,
      "extra": null,
      "categoryUuid": "859dd20a-242f-44ee-9120-091803dd43af",
      "accountUuid": "0e31f1f6-aacd-42f9-adbe-99321b0a2953"
    },
    {
      "uuid": "7b0c7208-d6a8-4525-9440-b72a328b1821",
      "createdDate": "2024-04-01T18:26:58.965",
      "transactionDate": "2024-04-01T18:26:44.175",
      "title": "test",
      "amount": -1.0,
      "currency": "EUR",
      "subtype": null,
      "extra": null,
      "categoryUuid": "859dd20a-242f-44ee-9120-091803dd43af",
      "accountUuid": "0e31f1f6-aacd-42f9-adbe-99321b0a2953"
    }
```

**Comment by sadespresso** [comment] 2024-11-10 15:52
I am not sure how I can reproduce this, so closing this for now.

On an unrelated note, 0.8.1 will export JSONs with UTC timezones

**Closed by sadespresso** 2024-11-10 15:52 UTC
Labels: bug, help wanted
