### ISSUE TITLE
[FEAT] - Search in account icon

### ISSUE THREAD

**Issue by albertorizzi** [flow-mn/flow#92] opened 2024-03-20 20:03 UTC
### Description

I'm creating a new account. When I select an icon, it would be better if there was the possibility to search icon. For example, I would search Revolut, because there are a lot of icons and I don't see Revolut icon.

![image](https://github.com/flow-mn/flow/assets/48057685/5e0675a4-be39-450c-a67f-437021fd930a)

**Comment by sadespresso** [comment] 2024-03-21 12:28
Closing as this is a duplicate of #61

**Closed by sadespresso** 2024-03-21 12:28 UTC
Labels: duplicate
